[build]
  publish = "_build_"
  # Allows overriding metadata.json via env var
  command = "[ \"$METADATA_JSON\" ] && echo $METADATA_JSON > _11ty/_data/metadata.json; yarn build"

[build.environment]
  INPUT = "_11ty"
  INCLUDES = "./_11ty/_includes"
  DATA = "./_11ty/_data"
  OUTPUT = "_build_"
  PLUGINS = "_11ty-plugins"
  COLLECTION = "_11ty-collection"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[headers]]
  for = "*.avif"
    [headers.values]
      Content-Type = "image/avif"
      Content-Disposition = "inline"
