#!/usr/bin/env node

const { build } = require("esbuild");
const glob = require("tiny-glob");
const path = require("path");
const args = process.argv.slice(2);

(async () => {
  let entryPoints = await glob(
    path.resolve(process.env.SRC, "js", "*.{js,mjs}")
  );
  build({
    entryPoints,
    outdir: path.resolve(process.env.OUTPUT, "js"),
    //    bundle: true,
    sourcemap: true,
    minify: true,
    format: "esm",
    watch: args.includes("--watch"),
  }).catch((e) => console.error(e.message));
})();
