#!/usr/bin/env node

const esbuild = require("esbuild");
const path = require("path");
const args = process.argv.slice(2);

esbuild
  .build({
    entryPoints: [path.resolve(process.env.SRC, "main.js")],
    outfile: path.resolve(process.env.OUTPUT, "js/min.js"),
    bundle: true,
    sourcemap: true,
    minify: true,
    format: "iife",
    watch: args.includes("--watch"),
  })
  .catch((e) => console.error(e.message));
